version: '3.8'

services:
  app:
    build: .
    ports:
      - "${PORT:-5000}:${PORT:-5000}"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=${PORT:-5000}
      - DB_HOST=db
      - DB_USERNAME=${DB_USERNAME:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-1234}
      - DB_NAME=${DB_NAME:-pearmonie}
      - JWT_SECRET=${JWT_SECRET:-your_secret_key_here}
      - BASE_URL=${BASE_URL:-http://localhost:5000}
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=${DB_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-1234}
      - POSTGRES_DB=${DB_NAME:-pearmonie}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
